# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d39c3903d68842709952c303bea152a50b049b992a40bf05cd468baa41c217a7b75fd881554f774577d1be920da4f94693fdc3794bb3d4567e779179faaa789

test:
  secret_key_base: b0cef286051a5df72de0b6dbe8c97cc55d3193f3fc4c70ec4755e9f16bf1d2db2aeb0cb479ef9fa1cdaec809dbd545ed5e64d97dbe048fab6dc7fe45554dafea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
